### ISSUE TITLE
Version of clang ?

### ISSUE THREAD

**Issue by wichtounet** [mikael-s-persson/templight#28]
Hi, 

Can you indicate which version of clang is officially supported ? I tried with the trunk version of clang and I got a conflict with the patch. 

Thanks

**Comment by r0mai** [comment]
[metashell](https://github.com/sabel83/metashell) currently uses r252870, it works nicely with that. Unfortunately the patch has to be updated quite often so it can applied cleanly to trunk.

**Comment by wichtounet** [comment]
I've fixed the issue with r242645 (found in another issue). It worked, but I haven't found a way to handle the too large files generated by the tool. I'll continue trying.

**Comment by r0mai** [comment]
Just a guess, but if you have problems with Google Protobuf rejecting the file due to it's size, then try to use the ThinProtobuf implementation by Mikael in this repo:

https://github.com/mikael-s-persson/templight-tools/tree/master/include/templight

Metashell uses this, and we had no problems with it. It's also faster than the official Protobuf implementation.

**Comment by wichtounet** [comment]
Thanks, but I don't think the problem is at this level. The conversion went ok, but the resulting SVG (pbf -> (templight-convert) -> .dot -> (dot) -> .svg) is way too large to be visualized and I had issues with Templar to open it (the issue is open and the author responded to me). I'll try with KCacheGrind once I get time to install a new VM.
