### ISSUE TITLE
Readme does not mention templight_clang_patch.diff

### ISSUE THREAD

**Issue by CraigMacomber** [mikael-s-persson/templight#66]
I followed the instruction in the readme. This means I used latest clang and llvm, and did not apply templight_clang_patch.diff since it is not mentioned.

It seems to have working output data (after a couple fixes): it is unclear to me if I need to apply templight_clang_patch.diff or not. What does the patch actually do?

Additionally templight_clang_version.txt is not mentioned in the readme.

Should the readme be updated to suggest pulling the revisions listed in templight_clang_version.txt and to then to apply templight_clang_patch.diff? If so, I can produce a pull request to do this and confirm that it works.

**Comment by sabel83** [comment]
The templight patch has been merged into Clang. If you use the latest Clang code, you will get an already patched version, which you don't need to patch.

The patched Clang (without the templight utility) can produce YAML output about the template instantiations, mainly for testing the patch itself, however, it turned out to be useful for utilities like Metashell as well. However, the YAML output has no profiling information. We are planning to add this as well - this is what ` templight_clang_patch.diff` and the corresponding `templight_clang_version.txt` you can find in this repository are for. You can safely ignore them.

Thank you for pointing this out, we will clean this repository up to avoid confusion.
